persistence:  
  enabled: true
  storageClassName: "gp2"

adminPassword: "grafana2021"

datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
    - name: Prometheus
      type: prometheus
      url: http://helm-prometheus-server.prometheus-ns.svc.cluster.local
      access: proxy
      isDefault: true 