persistence:  
  enabled: true
  storageClassName: "gp2"


datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
    - name: Prometheus
      type: prometheus
      url: http://helm-prometheus-server.prometheus.svc.cluster.local
      access: proxy
      isDefault: true 