apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets 
type: Opaque
data:
  postgres-user: cG9zdGdyZXM=
  postgres-password: cG9zdGdyZXMyMDIw
  pgadmin-password: cGdhZG1pbjIwMjA=
  pgadmin-email: bmlja0BnbWFpbC5jb20=
 #pg-db-password: postgres2020