apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  selector:
    app: postgres
  ports:
  - name: tcp-postgres
    port: 5432 #service port
    targetPort: 5432 #container port
    protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  name: pgadmin-service 
spec:
  selector:
    app: pgadmin
  ports:
  - name: tcp-pgadmin   
    port: 8080 #service port
    targetPort: 80 #container port
    protocol: TCP
  

---

---
apiVersion: v1
kind: Service
metadata:
  name: web-service 
spec:
  selector:
    app: web
  ports:
  - name: tcp-web   
    port: 80 #service port
    targetPort: 80 #container port
    protocol: TCP
  